In [184]:
!jt -r

Reset css and font defaults in:
C:\Users\timot\.jupyter\custom &
C:\Users\timot\AppData\Roaming\jupyter\nbextensions


In [177]:
!jt -t chesterish -T -N -fs 95 -altp -tfs 12 -nfs 115 -cellw 88% -T

In [2]:
import numpy as np
import scipy as sp
import struct
import glob
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import time
from numba import int64, int32, float32, boolean, jitclass, char, njit, jit
import numba
import sys
from astropy.table import Table
from astropy.table import Column
from astropy.io import ascii
%matplotlib inline

In [4]:
# Calculates the angles between high symmetry lattice planes for any arbitrary crystal structure
class angles:
    def __init__(self, varss):
        self.real = varss[0];
        self.ang = varss[1];
        a=self.real[0]; b=self.real[1]; c=self.real[2]; Alpha=self.ang[0]*2*np.pi/360; Beta=self.ang[1]*2*np.pi/360; Gamma=self.ang[2]*2*np.pi/360; #angles converted to radians
        self.vol = a*b*c*np.sqrt(1-(np.cos(Alpha))**2-(np.cos(Beta))**2-(np.cos(Gamma))**2+2*np.cos(Alpha)*np.cos(Beta)*np.cos(Gamma));
        self.Gstar = (2*np.pi)**2/(self.vol**2)*np.array([[b**2*c**2*np.sin(Alpha)**2, a*b*c**2*(np.cos(Alpha)*np.cos(Beta) - np.cos(Gamma)), a*b**2*c*(np.cos(Alpha)*np.cos(Gamma) - np.cos(Beta))], [a*b*c**2*(np.cos(Alpha)*np.cos(Beta) - np.cos(Gamma)), a**2*c**2*np.sin(Beta)**2, a**2*b*c*(np.cos(Beta)*np.cos(Gamma) - np.cos(Alpha))], [a*b**2*c*(np.cos(Alpha)*np.cos(Gamma) - np.cos(Beta)), a**2*b*c*(np.cos(Beta)*np.cos(Gamma) - np.cos(Alpha)), a**2*b**2*np.sin(Gamma)**2]]);
        # Gstar is the reciprocal space metric tensor
        self.highsymm = np.array(varss[2]);
        self.highsymmstr = np.zeros(len(self.highsymm)).astype(str)
        for i in range(len(self.highsymm)):
            self.highsymmstr[i] =str(self.highsymm[i])
        self.table = np.round(np.arccos(np.divide(np.inner(self.highsymm,np.dot(self.highsymm,self.Gstar)),np.sqrt(np.tensordot(np.diag(np.inner(self.highsymm,np.dot(self.highsymm,self.Gstar))),np.diag(np.inner(self.highsymm,np.dot(self.highsymm,self.Gstar))),axes=0))))*360/(2*np.pi),decimals=5);
    def ttable(self):
        self.astropytable = Table(self.table,names = self.highsymm);
        self.astropytable.add_column(Column(self.highsymmstr,name = 'Angle (\N{DEGREE SIGN})'),index=0);
        #print(astropytable)
       # for i in range(len(self.highsym)):
       #     self.table[i] = np.divide(np.multiply(self.highsymm[i],self.highsymm) 
  #  def crossproduct(v1,v2,self):
  #      self.cp = [v1/]

In [5]:
planes = [[0,1,0],[-1,0,1]]#planes = [[0,1,1],[0,1,-1],[1,0,1],[1,0,-1],[1,1,0],[1,-1,0],[0,-1,-1],[0,-1,1],[-1,0,-1],[-1,0,1],[-1,-1,0],[-1,1,0]] # the set of planes to calculate the angles between. 
Ruby = angles([[4.766,4.766,13.01],[90,90,120],planes])

In [6]:
Ruby.ttable()
Ruby.astropytable.pprint(max_lines=30,max_width=1000)

Angle (°)  [0 1 0] [-1  0  1]
---------- ------- ----------
   [0 1 0]     0.0     118.46
[-1  0  1]  118.46        0.0


In [11]:
#planes = [[0,0,1],[0,1,0],[0,1,1],[0,1,-1],[1,0,0],[1,0,1],[1,0,-1],[1,1,0],[1,-1,0],[1,1,1],[1,1,-1],[1,-1,1],[1,-1,-1],[0,0,-1],[0,-1,0],[0,-1,-1],[0,-1,1],[-1,0,0],[-1,0,-1],[-1,0,1],[-1,-1,0],[-1,1,0],[-1,-1,-1],[-1,-1,1],[-1,1,-1],[-1,1,1]] # the set of planes to calculate the angles between. 
planes = [[1,0,1],[0,1,0],[-1,0,0.742]] # the set of planes to calculate the angles between. 
#planes = [[-10,0,7],[0,2,0]]
          #planes = [[0,1,1],[0,1,-1],[1,0,1],[1,0,-1],[1,1,0],[1,-1,0],[0,-1,-1],[0,-1,1],[-1,0,-1],[-1,0,1],[-1,-1,0],[-1,1,0]] # the set of planes to calculate the angles between. 
Cr8mon = angles([[25.33,16.68,31.039],[90,109.81,90],planes])
Cr8tet = angles([[19.5,19.5,16.801],[90,90,90],planes]) # find where the lattice vectors came from.

In [12]:
print('tetragonal')
tet.ttable()
tet.astropytable.pprint(max_lines=30,max_width=1000)

tetragonal
      Angle (°)        [1. 0. 1.] [0. 1. 0.] [-1.     0.     0.742]
---------------------- ---------- ---------- ----------------------
            [1. 0. 1.]        0.0       90.0               90.01286
            [0. 1. 0.]       90.0        0.0                   90.0
[-1.     0.     0.742]   90.01286       90.0                    0.0


In [13]:
print('monoclinic')
mon.ttable()
mon.astropytable.pprint(max_lines=30,max_width=1000)

monoclinic
Angle (°)  [0 0 1] [0 1 0] [0 1 1] [ 0  1 -1] [1 0 0] [1 0 1] [ 1  0 -1] [1 1 0] [ 1 -1  0] [1 1 1] [ 1  1 -1] [ 1 -1  1] [ 1 -1 -1] [ 0  0 -1] [ 0 -1  0] [ 0 -1 -1] [ 0 -1  1] [-1  0  0] [-1  0 -1] [-1  0  1] [-1 -1  0] [-1  1  0] [-1 -1 -1] [-1 -1  1] [-1  1 -1] [-1  1  1]
---------- ------- ------- ------- ---------- ------- ------- ---------- ------- ---------- ------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
   [0 0 1]     0.0    90.0   60.27     119.73   70.19   39.17     116.89   78.79      78.79   55.97     105.59      55.97     105.59      180.0       90.0     119.73      60.27     109.81     140.83      63.11     101.21     101.21     124.03      74.41     124.03      74.41
   [0 1 0]    90.0     0.0   29.73      29.73    90.0    90.0       90.0   34.99     145.01    46.2      36.44      133.8     143.56       90.0      180.0     15

In [3]:
planes = [[1,1,1],[1,1,-1],[-1,-1,-1],[-1,-1,1],[0,0,2],[0,0,-2],[2,2,0],[2,2,2],[2,2,-2],[1,1,-3],[-1,-1,-3]] # the set of planes to calculate the angles between. 
#planes = [[-10,0,7],[0,2,0]]
          #planes = [[0,1,1],[0,1,-1],[1,0,1],[1,0,-1],[1,1,0],[1,-1,0],[0,-1,-1],[0,-1,1],[-1,0,-1],[-1,0,1],[-1,-1,0],[-1,1,0]] # the set of planes to calculate the angles between. 
HTO = angles([[10.021,10.021,10.021],[90,90,90],planes])

In [4]:
print('HTO')
HTO.ttable()
HTO.astropytable.pprint(max_lines=30,max_width=1000)

HTO
Angle (°)   [1 1 1]  [ 1  1 -1] [-1 -1 -1] [-1 -1  1]  [0 0 2]  [ 0  0 -2]  [2 2 0]   [2 2 2]  [ 2  2 -2] [ 1  1 -3] [-1 -1 -3]
---------- --------- ---------- ---------- ---------- --------- ---------- --------- --------- ---------- ---------- ----------
   [1 1 1]       0.0   70.52878      180.0  109.47122  54.73561  125.26439  35.26439       0.0   70.52878  100.02499  150.50379
[ 1  1 -1]  70.52878        0.0  109.47122      180.0 125.26439   54.73561  35.26439  70.52878        0.0   29.49621   79.97501
[-1 -1 -1]     180.0  109.47122        0.0   70.52878 125.26439   54.73561 144.73561     180.0  109.47122   79.97501   29.49621
[-1 -1  1] 109.47122      180.0   70.52878        0.0  54.73561  125.26439 144.73561 109.47122      180.0  150.50379  100.02499
   [0 0 2]  54.73561  125.26439  125.26439   54.73561       0.0      180.0      90.0  54.73561  125.26439   154.7606   154.7606
[ 0  0 -2] 125.26439   54.73561   54.73561  125.26439     180.0        0.0      90.0 125.26439   54.